In [1]:
import numpy as np

t = np.array([[1, 2], [3, 4]])

t

array([[1, 2],
       [3, 4]])

In [2]:
np.einsum('ij', t)

array([[1, 2],
       [3, 4]])

In [3]:
np.einsum('ji', t)

array([[1, 3],
       [2, 4]])

In [4]:
np.einsum('ii', t)

5

In [5]:
np.einsum('jj', t)

5